//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperheroesInc.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Character
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Character()
        {
            this.CourseCharacters = new HashSet<CourseCharacter>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Alias { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<int> SourceOfPowers { get; set; }
        public Nullable<int> Age { get; set; }
        public string Sex { get; set; }
        public int AlignmentID { get; set; }
    
        public virtual Alignment Alignment { get; set; }
        public virtual SourceOfPower SourceOfPower { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseCharacter> CourseCharacters { get; set; }
    }
}
